[package]
name = "omni-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
omni-common = { path = "../common" }
duckdb.workspace = true
calamine.workspace = true
csv.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true
thiserror.workspace = true
rust_decimal.workspace = true
